const constants = {
  ADD_COLOR: "ADD_COLOR",
  RATE_COLOR: "RATE_COLOR",
  SELECT_COLOR: "SELECT_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  ADD_PALLET: "ADD_PALLET",
  ADD_PALLET_COLORS: "ADD_PALLET_COLORS"
  // REMOVE_PALLET_COLOR: "REMOVE_PALLET_COLOR"
};

export default constants;
