const constants = {
  ADD_COLOR: "ADD_COLOR",
  RATE_COLOR: "RATE_COLOR",
  SELECT_COLOR: "SELECT_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  ADD_PALETTE: "ADD_PALETTE",
  ADD_PALETTE_COLORS: "ADD_PALETTE_COLORS",
  SELECT_PALETTE: "SELECT_PALETTE"
  // REMOVE_PALLET_COLOR: "REMOVE_PALLET_COLOR"
};

export default constants;
