const constants = {
  ADD_COLOR: "ADD_COLOR",
  RATE_COLOR: "RATE_COLOR",
  SELECT_COLOR: "SELECT_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  ADD_PALETTE: "ADD_PALETTE",
  ADD_PALETTE_COLORS: "ADD_PALETTE_COLORS",
  SELECT_PALETTE: "SELECT_PALETTE",
  TOGGLE_VISIBILITY: "TOGGLE_VISIBILITY",
  SELECT_PCOLOR: "SELECT_PCOLOR",
  REMOVE_PALETTE_COLOR: "REMOVE_PALLET_COLOR",
  ADD_ALERT: "ADD_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
  REMOVE_PALETTE: "REMOVE_PALETTE"
};

export default constants;
